/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	sbezverkiov1 "github.com/sbezverk/nsm2nsm/pkg/apis/sbezverk.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeServerEndpoints implements ServerEndpointInterface
type FakeServerEndpoints struct {
	Fake *FakeSbezverkV1
	ns   string
}

var serverendpointsResource = schema.GroupVersionResource{Group: "sbezverk.io", Version: "v1", Resource: "serverendpoints"}

var serverendpointsKind = schema.GroupVersionKind{Group: "sbezverk.io", Version: "v1", Kind: "ServerEndpoint"}

// Get takes name of the serverEndpoint, and returns the corresponding serverEndpoint object, and an error if there is any.
func (c *FakeServerEndpoints) Get(name string, options v1.GetOptions) (result *sbezverkiov1.ServerEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serverendpointsResource, c.ns, name), &sbezverkiov1.ServerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sbezverkiov1.ServerEndpoint), err
}

// List takes label and field selectors, and returns the list of ServerEndpoints that match those selectors.
func (c *FakeServerEndpoints) List(opts v1.ListOptions) (result *sbezverkiov1.ServerEndpointList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serverendpointsResource, serverendpointsKind, c.ns, opts), &sbezverkiov1.ServerEndpointList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &sbezverkiov1.ServerEndpointList{ListMeta: obj.(*sbezverkiov1.ServerEndpointList).ListMeta}
	for _, item := range obj.(*sbezverkiov1.ServerEndpointList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serverEndpoints.
func (c *FakeServerEndpoints) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serverendpointsResource, c.ns, opts))

}

// Create takes the representation of a serverEndpoint and creates it.  Returns the server's representation of the serverEndpoint, and an error, if there is any.
func (c *FakeServerEndpoints) Create(serverEndpoint *sbezverkiov1.ServerEndpoint) (result *sbezverkiov1.ServerEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serverendpointsResource, c.ns, serverEndpoint), &sbezverkiov1.ServerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sbezverkiov1.ServerEndpoint), err
}

// Update takes the representation of a serverEndpoint and updates it. Returns the server's representation of the serverEndpoint, and an error, if there is any.
func (c *FakeServerEndpoints) Update(serverEndpoint *sbezverkiov1.ServerEndpoint) (result *sbezverkiov1.ServerEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serverendpointsResource, c.ns, serverEndpoint), &sbezverkiov1.ServerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sbezverkiov1.ServerEndpoint), err
}

// Delete takes name of the serverEndpoint and deletes it. Returns an error if one occurs.
func (c *FakeServerEndpoints) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(serverendpointsResource, c.ns, name), &sbezverkiov1.ServerEndpoint{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServerEndpoints) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serverendpointsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &sbezverkiov1.ServerEndpointList{})
	return err
}

// Patch applies the patch and returns the patched serverEndpoint.
func (c *FakeServerEndpoints) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *sbezverkiov1.ServerEndpoint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serverendpointsResource, c.ns, name, data, subresources...), &sbezverkiov1.ServerEndpoint{})

	if obj == nil {
		return nil, err
	}
	return obj.(*sbezverkiov1.ServerEndpoint), err
}
