// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serverendpoints.proto

package serverendpoints

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerPing struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPing) Reset()         { *m = ServerPing{} }
func (m *ServerPing) String() string { return proto.CompactTextString(m) }
func (*ServerPing) ProtoMessage()    {}
func (*ServerPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_serverendpoints_131a71fe8acdd7d4, []int{0}
}
func (m *ServerPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPing.Unmarshal(m, b)
}
func (m *ServerPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPing.Marshal(b, m, deterministic)
}
func (dst *ServerPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPing.Merge(dst, src)
}
func (m *ServerPing) XXX_Size() int {
	return xxx_messageInfo_ServerPing.Size(m)
}
func (m *ServerPing) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPing.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPing proto.InternalMessageInfo

func (m *ServerPing) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ServerPong struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPong) Reset()         { *m = ServerPong{} }
func (m *ServerPong) String() string { return proto.CompactTextString(m) }
func (*ServerPong) ProtoMessage()    {}
func (*ServerPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_serverendpoints_131a71fe8acdd7d4, []int{1}
}
func (m *ServerPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPong.Unmarshal(m, b)
}
func (m *ServerPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPong.Marshal(b, m, deterministic)
}
func (dst *ServerPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPong.Merge(dst, src)
}
func (m *ServerPong) XXX_Size() int {
	return xxx_messageInfo_ServerPong.Size(m)
}
func (m *ServerPong) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPong.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPong proto.InternalMessageInfo

func (m *ServerPong) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerPing)(nil), "serverendpoints.ServerPing")
	proto.RegisterType((*ServerPong)(nil), "serverendpoints.ServerPong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerPingPongClient is the client API for ServerPingPong service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerPingPongClient interface {
	ServerPingPong(ctx context.Context, in *ServerPing, opts ...grpc.CallOption) (*ServerPong, error)
}

type serverPingPongClient struct {
	cc *grpc.ClientConn
}

func NewServerPingPongClient(cc *grpc.ClientConn) ServerPingPongClient {
	return &serverPingPongClient{cc}
}

func (c *serverPingPongClient) ServerPingPong(ctx context.Context, in *ServerPing, opts ...grpc.CallOption) (*ServerPong, error) {
	out := new(ServerPong)
	err := c.cc.Invoke(ctx, "/serverendpoints.ServerPingPong/ServerPingPong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerPingPongServer is the server API for ServerPingPong service.
type ServerPingPongServer interface {
	ServerPingPong(context.Context, *ServerPing) (*ServerPong, error)
}

func RegisterServerPingPongServer(s *grpc.Server, srv ServerPingPongServer) {
	s.RegisterService(&_ServerPingPong_serviceDesc, srv)
}

func _ServerPingPong_ServerPingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerPing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerPingPongServer).ServerPingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverendpoints.ServerPingPong/ServerPingPong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerPingPongServer).ServerPingPong(ctx, req.(*ServerPing))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerPingPong_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverendpoints.ServerPingPong",
	HandlerType: (*ServerPingPongServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerPingPong",
			Handler:    _ServerPingPong_ServerPingPong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serverendpoints.proto",
}

func init() {
	proto.RegisterFile("serverendpoints.proto", fileDescriptor_serverendpoints_131a71fe8acdd7d4)
}

var fileDescriptor_serverendpoints_131a71fe8acdd7d4 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x4a, 0xcd, 0x4b, 0x29, 0xc8, 0xcf, 0xcc, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x47, 0x13, 0x56, 0x52, 0xe0, 0xe2, 0x0a, 0x06, 0x0b, 0x05, 0x64, 0xe6, 0xa5,
	0x0b, 0x09, 0x71, 0xb1, 0xa4, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x48, 0x2a, 0xf2, 0xb1, 0xab, 0x30, 0x8a, 0xe1, 0xe2, 0x43, 0x98, 0x01, 0x56, 0xe5, 0x85,
	0x21, 0x22, 0xad, 0x87, 0xee, 0x20, 0x84, 0x02, 0x29, 0x9c, 0x92, 0xf9, 0x79, 0xe9, 0x49, 0x6c,
	0x60, 0x97, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x46, 0x1b, 0x62, 0xb8, 0xd2, 0x00, 0x00,
	0x00,
}
