/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	sbezverkiov1 "github.com/sbezverk/nsm2nsm/pkg/apis/sbezverk.io/v1"
	versioned "github.com/sbezverk/nsm2nsm/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sbezverk/nsm2nsm/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/sbezverk/nsm2nsm/pkg/client/listers/sbezverk.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ServerEndpointInformer provides access to a shared informer and lister for
// ServerEndpoints.
type ServerEndpointInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ServerEndpointLister
}

type serverEndpointInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewServerEndpointInformer constructs a new informer for ServerEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServerEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredServerEndpointInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredServerEndpointInformer constructs a new informer for ServerEndpoint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredServerEndpointInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SbezverkV1().ServerEndpoints(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SbezverkV1().ServerEndpoints(namespace).Watch(options)
			},
		},
		&sbezverkiov1.ServerEndpoint{},
		resyncPeriod,
		indexers,
	)
}

func (f *serverEndpointInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredServerEndpointInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *serverEndpointInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sbezverkiov1.ServerEndpoint{}, f.defaultInformer)
}

func (f *serverEndpointInformer) Lister() v1.ServerEndpointLister {
	return v1.NewServerEndpointLister(f.Informer().GetIndexer())
}
