---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsm2nsm-client
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsm2nsm-client
  namespace: default
rules:
- apiGroups: ["*"] 
  resources: ["namespaces"]
  verbs: ["get,list"]
- apiGroups: ["sbezverk.io"] 
  resources: ["*"]
  verbs: ["*"]  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsm2nsm-client
  namespace: default
subjects:
- kind: ServiceAccount
  namespace: default
  name: nsm2nsm-client
roleRef:
  kind: Role
  name: nsm2nsm-client
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: nsm2nsm-client-1
    spec:
      serviceAccount: nsm2nsm-client
      containers:
        - image: 192.168.80.240:4000/ligato/nsm2nsm-client:latest
          name: nsm2nsm-client
          imagePullPolicy: Always
metadata:
   name: nsm2nsm-client-1
   namespace: default